### ISSUE TITLE
Issue with Yolo.py

### ISSUE THREAD

**Issue by DanielNewsom** [Merkie/yolo-api#1]
code? ******
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\yolo-api-master\exampleuseage.py", line 16, in <module>
    y.loginWithVerfCode(i)
  File "C:\Users\Owner\Desktop\yolo-api-master\yolo.py", line 56, in loginWithVerfCode
    self.sesskey = j['result']
KeyError: 'result'

I ran it straight from the Example and im getting this error. Not too  sure how it works so dont know how to fix it.

**Comment by DanielNewsom** [comment]
Thought it was because my YOLO wasnt installed correctly but now i have no idea

**Comment by DanielNewsom** [comment]
Looked into J and it was {'code': 141, 'error': 'No user found'}. Not sure how there is no user when i use YOLO on this phone with snapchat linked with phone number

**Comment by Merkie** [comment]
link your phone number.
